version: '3'

services:
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx_data/certbot/conf:/etc/letsencrypt
      - ./nginx_data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
