[node]

detect-drivers = false

[relay]

url = "http://android:4723/wd/hub"
status-endpoint = "/status"

configs = [
    "1", "{\"browserName\": \"Samsung Galaxy S7\", \"platformName\": \"android\", \"appium:platformVersion\": \"7.1.1\"}"
]
