version: "3"
services:

  chrome:
    image: selenium/standalone-chrome
    hostname: chrome
    shm_size: 2g
    ports:
      - "7900:7900"
      - "4444:4444"
    restart: unless-stopped

  selenium_script:
    build: "./pythonbuild"
    restart: unless-stopped
    depends_on:
      - chrome

